# frozen_string_literal: true

# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!

require "gapic/rest"
require "google/cloud/compute/v1/compute_small_pb"

module Google
  module Cloud
    module Compute
      module V1
        module Networks
          module Rest
            ##
            # REST service stub for the Networks service.
            #
            class ServiceStub
              ##
              # Create a new Networks REST service stub object.
              #
              # @param endpoint [String]
              #   The hostname or hostname:port of the service endpoint.
              #   Defaults to `"localhost:7469"`.
              #
              # @param credentials [Google::Auth::Credentials]
              #   Credentials to send with calls in form of a googleauth credentials object.
              #   (see the [googleauth docs](https://googleapis.dev/ruby/googleauth/latest/index.html))
              #
              def initialize endpoint:, credentials:
                @client_stub = ::Gapic::Rest::ClientStub.new endpoint: endpoint, credentials: credentials
              end

              # Service calls

              ##
              # Adds a peering to the specified network.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::AddPeeringNetworkRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Operation]
              def add_peering request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::AddPeeringNetworkRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/global/networks/#{request_pb.network}/addPeering"
                body = request_pb.networks_add_peering_request_resource.to_json

                result_json = @client_stub.make_post_request(
                  uri:     uri,
                  body:    body,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Operation.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Deletes the specified network.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::DeleteNetworkRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Operation]
              def delete request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::DeleteNetworkRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/global/networks/#{request_pb.network}"

                result_json = @client_stub.make_delete_request(
                  uri:     uri,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Operation.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Returns the specified network. Gets a list of available networks by making a list() request.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::GetNetworkRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Network]
              def get request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::GetNetworkRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/global/networks/#{request_pb.network}"

                result_json = @client_stub.make_get_request(
                  uri:     uri,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Network.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Creates a network in the specified project using the data included in the request.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::InsertNetworkRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Operation]
              def insert request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::InsertNetworkRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/global/networks"
                body = request_pb.network_resource.to_json

                result_json = @client_stub.make_post_request(
                  uri:     uri,
                  body:    body,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Operation.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Retrieves the list of networks available to the specified project.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::ListNetworksRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::NetworkList]
              def list request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::ListNetworksRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/global/networks"

                result_json = @client_stub.make_get_request(
                  uri:     uri,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::NetworkList.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Lists the peering routes exchanged over peering connection.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::ListPeeringRoutesNetworksRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::ExchangedPeeringRoutesList]
              def list_peering_routes request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::ListPeeringRoutesNetworksRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/global/networks/#{request_pb.network}/listPeeringRoutes"

                result_json = @client_stub.make_get_request(
                  uri:     uri,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::ExchangedPeeringRoutesList.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Patches the specified network with the data included in the request. Only the following fields can be modified: routingConfig.routingMode.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::PatchNetworkRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Operation]
              def patch request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::PatchNetworkRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/global/networks/#{request_pb.network}"
                body = request_pb.network_resource.to_json

                result_json = @client_stub.make_patch_request(
                  uri:     uri,
                  body:    body,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Operation.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Removes a peering from the specified network.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::RemovePeeringNetworkRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Operation]
              def remove_peering request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::RemovePeeringNetworkRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/global/networks/#{request_pb.network}/removePeering"
                body = request_pb.networks_remove_peering_request_resource.to_json

                result_json = @client_stub.make_post_request(
                  uri:     uri,
                  body:    body,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Operation.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Switches the network mode from auto subnet mode to custom subnet mode.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::SwitchToCustomModeNetworkRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Operation]
              def switch_to_custom_mode request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::SwitchToCustomModeNetworkRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/global/networks/#{request_pb.network}/switchToCustomMode"

                result_json = @client_stub.make_post_request(
                  uri:     uri,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Operation.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Updates the specified network peering with the data included in the request Only the following fields can be modified: NetworkPeering.export_custom_routes, and NetworkPeering.import_custom_routes
              #
              # @param request_pb [::Google::Cloud::Compute::V1::UpdatePeeringNetworkRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Operation]
              def update_peering request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::UpdatePeeringNetworkRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/global/networks/#{request_pb.network}/updatePeering"
                body = request_pb.networks_update_peering_request_resource.to_json

                result_json = @client_stub.make_patch_request(
                  uri:     uri,
                  body:    body,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Operation.decode_json result_json[:body], { ignore_unknown_fields: true }
              end
            end
          end
        end
      end
    end
  end
end
