# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: schema/google/showcase/v1beta1/sequence.proto for package 'google.showcase.v1beta1'
# Original file comments:
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require 'schema/google/showcase/v1beta1/sequence_pb'

module Google
  module Showcase
    module V1beta1
      module SequenceService
        class Service

          include GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'google.showcase.v1beta1.SequenceService'

          rpc :CreateSequence, Google::Showcase::V1beta1::CreateSequenceRequest, Google::Showcase::V1beta1::Sequence
          rpc :GetSequenceReport, Google::Showcase::V1beta1::GetSequenceReportRequest, Google::Showcase::V1beta1::SequenceReport
          rpc :AttemptSequence, Google::Showcase::V1beta1::AttemptSequenceRequest, Google::Protobuf::Empty
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
