# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema/google/showcase/v1beta1/sequence.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'google/api/client_pb'
require 'google/api/field_behavior_pb'
require 'google/api/resource_pb'
require 'google/protobuf/duration_pb'
require 'google/protobuf/empty_pb'
require 'google/protobuf/timestamp_pb'
require 'google/rpc/status_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("schema/google/showcase/v1beta1/sequence.proto", :syntax => :proto3) do
    add_message "google.showcase.v1beta1.Sequence" do
      optional :name, :string, 1
      repeated :responses, :message, 2, "google.showcase.v1beta1.Sequence.Response"
    end
    add_message "google.showcase.v1beta1.Sequence.Response" do
      optional :status, :message, 1, "google.rpc.Status"
      optional :delay, :message, 2, "google.protobuf.Duration"
    end
    add_message "google.showcase.v1beta1.SequenceReport" do
      optional :name, :string, 1
      repeated :attempts, :message, 2, "google.showcase.v1beta1.SequenceReport.Attempt"
    end
    add_message "google.showcase.v1beta1.SequenceReport.Attempt" do
      optional :attempt_number, :int32, 1
      optional :attempt_deadline, :message, 2, "google.protobuf.Timestamp"
      optional :response_time, :message, 3, "google.protobuf.Timestamp"
      optional :attempt_delay, :message, 4, "google.protobuf.Duration"
      optional :status, :message, 5, "google.rpc.Status"
    end
    add_message "google.showcase.v1beta1.CreateSequenceRequest" do
      optional :sequence, :message, 1, "google.showcase.v1beta1.Sequence"
    end
    add_message "google.showcase.v1beta1.AttemptSequenceRequest" do
      optional :name, :string, 1
    end
    add_message "google.showcase.v1beta1.GetSequenceReportRequest" do
      optional :name, :string, 1
    end
  end
end

module Google
  module Showcase
    module V1beta1
      Sequence = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1beta1.Sequence").msgclass
      Sequence::Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1beta1.Sequence.Response").msgclass
      SequenceReport = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1beta1.SequenceReport").msgclass
      SequenceReport::Attempt = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1beta1.SequenceReport.Attempt").msgclass
      CreateSequenceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1beta1.CreateSequenceRequest").msgclass
      AttemptSequenceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1beta1.AttemptSequenceRequest").msgclass
      GetSequenceReportRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("google.showcase.v1beta1.GetSequenceReportRequest").msgclass
    end
  end
end
