source "https://rubygems.org"

gem "faraday"
#gem "gapic-common", path: "../gapic-common"
gem "google-cloud-compute-v1", path: "../google-cloud-compute-v1"
#gem "google-showcase", path: "../google-showcase-v1beta1"

# Specify your gem's dependencies in test_use_showcase_lib.gemspec
gemspec

gem "rake", "~> 12.0"
gem "minitest", "~> 5.0"
