# frozen_string_literal: true

# The MIT License (MIT)
#
# Copyright <YEAR> <COPYRIGHT HOLDER>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!

require "helper"
require "google/showcase/v1beta1/identity"
require 'faraday'
require 'json'

class ::Google::Showcase::V1beta1::Identity::ClientRestTest < Minitest::Test
  class ClientRestStub
    attr_accessor :call_rest_count, :requests

    def initialize(response, operation, &block)
      @response = response
      @operation = operation
      @block = block

      @call_rpc_count = 0
      @requests = []
    end

    def call_rpc(*args, **kwargs)
      @call_rest_count += 1

      @requests << @block&.call(*args, **kwargs)

      yield @response, @operation if block_given?

      @response
    end
  end

  # @param id [Int, String]
  # @return [Hash {String => String}]
  def create_user_hash(id)
    {
      'display_name' => "ExampleName#{id}",
      'email' => "ExampleName#{id}@example.com"
    }
  end

  def test_create_user_simple
    rest_options = {}
    client = ::Google::Showcase::V1beta1::Identity::ClientRest.new
    user = create_user_hash 100

    client.create_user({ user: user }) do |result, response|
      assert_equal 200, result[:status]

      result_user = JSON.parse(result[:body])
      assert_equal user['display_name'], result_user['displayName']

      request_user = JSON.parse(response.env.request_body)['user']
      assert_equal user['display_name'], request_user['displayName']
    end
  end

  def test_create_user
    rest_options = {}
    client = ::Google::Showcase::V1beta1::Identity::ClientRest.new

    user = create_user_hash 0
    # Use hash object
    client.create_user({ user: user }) do |result, response|
      assert_equal 200, result[:status]

      result_user = JSON.parse(result[:body])
      assert_equal user['display_name'], result_user['displayName']

      request_user = JSON.parse(response.env.request_body)['user']
      assert_equal user['display_name'], request_user['displayName']
   end

    user = create_user_hash 1
    # Use named arguments
    client.create_user user: user do |result, response|
      assert_equal 200, result[:status]

      result_user = JSON.parse(result[:body])
      assert_equal user['display_name'], result_user['displayName']

      request_user = JSON.parse(response.env.request_body)['user']
      assert_equal user['display_name'], request_user['displayName']
    end

    user = create_user_hash 2
    # Use protobuf object
    client.create_user ::Google::Showcase::V1beta1::CreateUserRequest.new(user: user) do |result, response|
      assert_equal 200, result[:status]

      result_user = JSON.parse(result[:body])
      assert_equal user['display_name'], result_user['displayName']

      request_user = JSON.parse(response.env.request_body)['user']
      assert_equal user['display_name'], request_user['displayName']
    end

    user = create_user_hash 3
    # Use hash object with options
    client.create_user({ user: user }, rest_options) do |result, response|
      assert_equal 200, result[:status]

      result_user = JSON.parse(result[:body])
      assert_equal user['display_name'], result_user['displayName']

      request_user = JSON.parse(response.env.request_body)['user']
      assert_equal user['display_name'], request_user['displayName']
    end

    user = create_user_hash 4
    # Use protobuf object with options
    client.create_user ::Google::Showcase::V1beta1::CreateUserRequest.new(user: user), rest_options do |result, response|
      assert_equal 200, result[:status]

      result_user = JSON.parse(result[:body])
      assert_equal user['display_name'], result_user['displayName']

      request_user = JSON.parse(response.env.request_body)['user']
      assert_equal user['display_name'], request_user['displayName']
    end
  end
end