# frozen_string_literal: true

# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated by gapic-generator-ruby. DO NOT EDIT!

require "gapic/rest"
require "google/cloud/compute/v1/compute_small_pb"

module Google
  module Cloud
    module Compute
      module V1
        module Projects
          module Rest
            ##
            # REST service stub for the Projects service.
            #
            class ServiceStub
              ##
              # Create a new Projects REST service stub object.
              #
              # @param endpoint [String]
              #   The hostname or hostname:port of the service endpoint.
              #   Defaults to `"localhost:7469"`.
              #
              # @param credentials [Google::Auth::Credentials]
              #   Credentials to send with calls in form of a googleauth credentials object.
              #   (see the [googleauth docs](https://googleapis.dev/ruby/googleauth/latest/index.html))
              #
              def initialize endpoint:, credentials:
                @client_stub = ::Gapic::Rest::ClientStub.new endpoint: endpoint, credentials: credentials
              end

              # Service calls

              ##
              # Disable this project as a shared VPC host project.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::DisableXpnHostProjectRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Operation]
              def disable_xpn_host request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::DisableXpnHostProjectRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/disableXpnHost"

                result_json = @client_stub.make_post_request(
                  uri:     uri,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Operation.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Disable a service resource (also known as service project) associated with this host project.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::DisableXpnResourceProjectRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Operation]
              def disable_xpn_resource request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::DisableXpnResourceProjectRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/disableXpnResource"
                body = request_pb.projects_disable_xpn_resource_request_resource.to_json

                result_json = @client_stub.make_post_request(
                  uri:     uri,
                  body:    body,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Operation.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Enable this project as a shared VPC host project.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::EnableXpnHostProjectRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Operation]
              def enable_xpn_host request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::EnableXpnHostProjectRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/enableXpnHost"

                result_json = @client_stub.make_post_request(
                  uri:     uri,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Operation.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Enable service resource (a.k.a service project) for a host project, so that subnets in the host project can be used by instances in the service project.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::EnableXpnResourceProjectRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Operation]
              def enable_xpn_resource request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::EnableXpnResourceProjectRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/enableXpnResource"
                body = request_pb.projects_enable_xpn_resource_request_resource.to_json

                result_json = @client_stub.make_post_request(
                  uri:     uri,
                  body:    body,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Operation.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Returns the specified Project resource.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::GetProjectRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Project]
              def get request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::GetProjectRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}"

                result_json = @client_stub.make_get_request(
                  uri:     uri,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Project.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Gets the shared VPC host project that this project links to. May be empty if no link exists.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::GetXpnHostProjectRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Project]
              def get_xpn_host request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::GetXpnHostProjectRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/getXpnHost"

                result_json = @client_stub.make_get_request(
                  uri:     uri,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Project.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Gets service resources (a.k.a service project) associated with this host project.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::GetXpnResourcesProjectsRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::ProjectsGetXpnResources]
              def get_xpn_resources request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::GetXpnResourcesProjectsRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/getXpnResources"

                result_json = @client_stub.make_get_request(
                  uri:     uri,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::ProjectsGetXpnResources.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Lists all shared VPC host projects visible to the user in an organization.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::ListXpnHostsProjectsRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::XpnHostList]
              def list_xpn_hosts request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::ListXpnHostsProjectsRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/listXpnHosts"
                body = request_pb.projects_list_xpn_hosts_request_resource.to_json

                result_json = @client_stub.make_post_request(
                  uri:     uri,
                  body:    body,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::XpnHostList.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Moves a persistent disk from one zone to another.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::MoveDiskProjectRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Operation]
              def move_disk request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::MoveDiskProjectRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/moveDisk"
                body = request_pb.disk_move_request_resource.to_json

                result_json = @client_stub.make_post_request(
                  uri:     uri,
                  body:    body,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Operation.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Moves an instance and its attached persistent disks from one zone to another.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::MoveInstanceProjectRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Operation]
              def move_instance request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::MoveInstanceProjectRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/moveInstance"
                body = request_pb.instance_move_request_resource.to_json

                result_json = @client_stub.make_post_request(
                  uri:     uri,
                  body:    body,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Operation.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Sets metadata common to all instances within the specified project using the data included in the request.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::SetCommonInstanceMetadataProjectRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Operation]
              def set_common_instance_metadata request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::SetCommonInstanceMetadataProjectRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/setCommonInstanceMetadata"
                body = request_pb.metadata_resource.to_json

                result_json = @client_stub.make_post_request(
                  uri:     uri,
                  body:    body,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Operation.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Sets the default network tier of the project. The default network tier is used when an address/forwardingRule/instance is created without specifying the network tier field.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::SetDefaultNetworkTierProjectRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Operation]
              def set_default_network_tier request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::SetDefaultNetworkTierProjectRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/setDefaultNetworkTier"
                body = request_pb.projects_set_default_network_tier_request_resource.to_json

                result_json = @client_stub.make_post_request(
                  uri:     uri,
                  body:    body,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Operation.decode_json result_json[:body], { ignore_unknown_fields: true }
              end

              ##
              # Enables the usage export feature and sets the usage export bucket where reports are stored. If you provide an empty request body using this method, the usage export feature will be disabled.
              #
              # @param request_pb [::Google::Cloud::Compute::V1::SetUsageExportBucketProjectRequest]
              #   A request object representing the call parameters. Required.
              # @param options [::Gapic::CallOptions]
              #   Overrides the default settings for this call, e.g, timeout, retries, etc. Optional.
              # @return [::Google::Cloud::Compute::V1::Operation]
              def set_usage_export_bucket request_pb, options:, &block
                request_json = JSON.parse ::Google::Cloud::Compute::V1::SetUsageExportBucketProjectRequest.encode_json(request_pb)

                uri = "/compute/v1/projects/#{request_pb.project}/setUsageExportBucket"
                body = request_pb.usage_export_location_resource.to_json

                result_json = @client_stub.make_post_request(
                  uri:     uri,
                  body:    body,
                  options: options,
                  &block
                )

                ::Google::Cloud::Compute::V1::Operation.decode_json result_json[:body], { ignore_unknown_fields: true }
              end
            end
          end
        end
      end
    end
  end
end
